### PR TITLE
Unblock P2P shuffle operations on CPU

### PR DESCRIPTION
**Pull request by charlesbluca**
Following up on #1067, this PR re-enables Dask's P2P shuffle algorithm to try and resolve the resulting test failures.

### CODE REVIEW

**Comment by charlesbluca** [comment]
Remaining test failures are on GPU, and seem to be caused by issues upstream, in particular `test_broadcast_join` and some of the queries fail when the P2P shuffle algorithm attempts to merge cuDF and pandas frames:

```python-traceback
Traceback (most recent call last):
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/distributed/shuffle/_shuffle.py", line 58, in shuffle_transfer
    return _get_worker_extension().add_partition(
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/distributed/shuffle/_worker_extension.py", line 629, in add_partition
    return sync(
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/distributed/utils.py", line 405, in sync
    raise exc.with_traceback(tb)
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/distributed/utils.py", line 378, in f
    result = yield future
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/distributed/shuffle/_worker_extension.py", line 507, in add_partition
    out = await self.offload(_)
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/distributed/shuffle/_worker_extension.py", line 132, in offload
    return await asyncio.get_running_loop().run_in_executor(
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/distributed/shuffle/_worker_extension.py", line 499, in _
    out = split_by_worker(
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/distributed/shuffle/_worker_extension.py", line 910, in split_by_worker
    df = df.merge(
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/cudf/core/dataframe.py", line 3991, in merge
    return merge_cls(
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/cudf/core/join/join.py", line 81, in __init__
    self._validate_merge_params(
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/cudf/core/join/join.py", line 391, in _validate_merge_params
    same_named_columns = set(lhs._data) & set(rhs._data)
TypeError: 'SingleBlockManager' object is not iterable
```

And queries involving string columns fail because Arrow attempts to access their `values` attribute, which isn't supported in cuDF:

```python-traceback
Traceback (most recent call last):
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/distributed/shuffle/_shuffle.py", line 58, in shuffle_transfer
    return _get_worker_extension().add_partition(
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/distributed/shuffle/_worker_extension.py", line 628, in add_partition
    shuffle = self.get_or_create_shuffle(shuffle_id, type=type, **kwargs)
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/distributed/shuffle/_worker_extension.py", line 879, in get_or_create_shuffle
    return sync(
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/distributed/utils.py", line 405, in sync
    raise exc.with_traceback(tb)
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/distributed/utils.py", line 378, in f
    result = yield future
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/distributed/shuffle/_worker_extension.py", line 709, in _get_or_create_shuffle
    shuffle = await self._refresh_shuffle(
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/distributed/shuffle/_worker_extension.py", line 758, in _refresh_shuffle
    "schema": pa.Schema.from_pandas(kwargs["empty"])
  File "pyarrow/types.pxi", line 1739, in pyarrow.lib.Schema.from_pandas
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 540, in dataframe_to_types
    values = c.values
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/cudf/core/single_column_frame.py", line 117, in values
    return self._column.values
  File "/raid/charlesb/mambaforge/envs/enable-p2p-gpu/lib/python3.8/site-packages/cudf/core/column/string.py", line 5551, in values
    raise TypeError("String Arrays is not yet implemented in cudf")
TypeError: String Arrays is not yet implemented in cudf
```

Given these limitations, I feel like it probably makes the most sense to globally disable P2P tests (since we can't reasonably predict when it's going to fail as we add new tests), and maybe introduce a warning if we detect that P2P is being used that it may fail on GPU tables? cc @ayushdg in case you have some thoughts here

**Comment by ayushdg** [comment]
Yeah. That sounds reasonable. We can set the config only on gpuCI tests (instead of globally), and add a warning when we detect p2p that it may fail on gpu tables. 
Ideally we'd only want to raise when users are using a query involving a GPU table. If it's feasible we can try checking at the end of table scan what type of df we have and warn accordingly. If that doesn't work as expected, a blanket warning for GPU tables sounds good

**Review by ayushdg — APPROVED** [review]
Thanks for following up. Do you want to open up an issue to remove the p2p config when https://github.com/dask/dask/pull/10043 lands?

**Comment by charlesbluca** [comment]
> Do you want to open up an issue to remove the p2p config when https://github.com/dask/dask/pull/10043 lands?

Yeah that was my plan, though I'm debating between bumping our min Dask version for this fix versus just emitting a warning when attempting the groupby apply call on a GPU table

**Pull request merged**
