### PR TITLE
Add metadata for wrap_fit when using GPU dataframes

### PR DESCRIPTION
**Pull request by ChrisJar**
Enables using `CREATE MODEL` with gpu dataframes and `wrap_fit=True`. Depends on dask-ml/#862.

### CODE REVIEW

**Comment by charlesbluca** [comment]
@ChrisJar it looks like dask/dask-ml#862 is in - is this ready to review?

**Comment by VibhuJawa** [comment]
I think this PR is no longer needed as now with this state of `dask-ml` below should just work as the default now is `infer` for predict .   See doc-string [here](https://ml.dask.org/modules/generated/dask_ml.wrappers.ParallelPostFit.html) . 


That is below works now:
```python
df = timeseries(freq="1d").reset_index(drop=True).compute()
df = cudf.from_pandas(df)
df['target'] = df['x']*df['y'] > 0

model = cuml.linear_model.LinearRegression()
model.fit(df[['x','y']], df['target'])

dask_model = dask_model = ParallelPostFit(model)
dask_cudf_df = dask_cudf.from_cudf(df, npartitions=2)
dask_model.predict(dask_cudf_df[['x','y']]).compute()

```

**Comment by VibhuJawa** [comment]
Can confirm below query with `cuML` and `dask-cuDF` now just works. :-D 

```python
model_query = '''
CREATE OR REPLACE MODEL my_model WITH (
    model_class = 'cuml.linear_model.LogisticRegression',
    wrap_predict = True,
    wrap_fit = False,
    target_column = 'target'
) AS (
    SELECT x, y, x*y > 0 AS target
    FROM timeseries
)
'''
predict_sql = """
        SELECT * FROM PREDICT(
            MODEL my_model,
            SELECT x, y FROM timeseries
        )
        """
df = timeseries(freq="1d").reset_index(drop=True).compute()
df = cudf.from_pandas(df)
df = dask_cudf.from_cudf(df, npartitions=2)
c.create_table('timeseries',input_table=df)


c.sql(model_query)
c.sql(predict_sql).compute()
```

**Comment by ChrisJar** [comment]
Awesome, thanks for letting me know. I'll close this PR

**Pull request closed without merging**
