### PR TITLE
Give `conda-forge` higher priority than `nvidia` in GPU environments

### PR DESCRIPTION
**Pull request by charlesbluca**
Subtle difference between the GPU environments in this repo versus those used in the GPU CI runs, but important because having `conda-forge` above `nvidia` prevents us from installing `cuda-toolkit`, which would otherwise cause some conflicts with `libcudf`'s recent addition of `libcufile` as a dependency.

### CODE REVIEW

**Comment by ayushdg** [comment]
Are the gpuCI errors here unrelated?

**Comment by charlesbluca** [comment]
rerun tests

**Comment by ayushdg** [comment]
rerun tests

**Comment by ayushdg** [comment]
rerun tests

**Pull request merged**
