### PR TITLE
Require UDF return type and update docs

### PR DESCRIPTION
**Pull request by brandon-b-miller**
Closes https://github.com/dask-contrib/dask-sql/issues/278.

Small PR that fixes a docs TODO and adds an error guard.

### CODE REVIEW

**Comment by quasiben** [comment]
@brandon-b-miller do you have thoughts on @ayushdg concerns over type inference in the above ?  I think this is the last concern and then we can merge

**Comment by brandon-b-miller** [comment]
Updating this shortly.

**Comment by brandon-b-miller** [comment]
Should fail in both cases now :)

**Comment by quasiben** [comment]
Thanks @brandon-b-miller !

**Pull request merged**
