### PR TITLE
Un-xfail queries 53 and 63

### PR DESCRIPTION
**Pull request by sarahyurick**
Investigating https://github.com/dask-contrib/dask-sql/issues/1164

cc @ayushdg

### CODE REVIEW

**Comment by ayushdg** [comment]
@brandon-b-miller still seeing errors similar to https://github.com/rapidsai/cudf/issues/13426 in CI with the latest nightly. Is it possible that the fix missed some edge cases (or apply via dask)

**Comment by brandon-b-miller** [comment]
> @brandon-b-miller still seeing errors similar to [rapidsai/cudf#13426](https://github.com/rapidsai/cudf/issues/13426) in CI with the latest nightly. Is it possible that the fix missed some edge cases (or apply via dask).
> 
> Here's the log for reference: https://gpuci.gpuopenanalytics.com/job/dask/job/dask-sql/job/prb/job/dask-sql-prb/2833/CUDA_VER=11.5,LINUX_VER=ubuntu18.04,PYTHON_VER=3.10,RAPIDS_VER=23.06/testReport/junit/tests.unit/test_queries/test_gpu_query_q53_sql_/

Looking into this 👍

**Comment by ayushdg** [comment]
Thanks for looking into this. As pointed out by @brandon-b-miller the issues seem to be coming from the nighty tests still using rapids 23.06 while the fix was merged into 23.08. 
We can revisit once all 23.08 packages for gpuci testing are available and we bump the version

**Comment by sarahyurick** [comment]
Will just wait on https://github.com/dask-contrib/dask-sql/pull/1170

**Comment by charlesbluca** [comment]
Think we should be good to close this - rolled the changed into #1170 and merged

**Pull request closed without merging**
